# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        run : |
          npm ci
          npm run build --if-present
  test:
    runs-on : ubuntu-latest
    env:
      PORT: ${{ secrets.PORT }}
      MYSQL_AWS_USERNAME: ${{ secrets.MYSQL_AWS_USERNAME }}
      MYSQL_AWS_PASSWORD: ${{ secrets.MYSQL_AWS_PASSWORD }}
      MYSQL_AWS_HOST: ${{ secrets.MYSQL_AWS_HOST }}
      MYSQL_AWS_DATABASE_TEST_DB: ${{ secrets.MYSQL_AWS_DATABASE_TEST_DB }}
      MYSQL_AWS_DATABASE: ${{ secrets.MYSQL_AWS_DATABASE }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

    strategy:
      matrix:
        os : [ubuntu-latest, windows-2022]
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm install
    - run: npm test
